table Sheet1
	lineageTag: 5b92f528-f9d8-40af-aba5-083ed5770367

	column LIB_COM_POSTAL
		dataType: string
		lineageTag: 8ef7ffa7-0708-4396-96ba-ee704da24862
		summarizeBy: none
		sourceColumn: LIB_COM_POSTAL

		annotation SummarizationSetBy = Automatic

	column LIBCOM
		dataType: string
		lineageTag: 665e85be-2c96-4b92-a63e-ac427f80288f
		summarizeBy: none
		sourceColumn: LIBCOM

		annotation SummarizationSetBy = Automatic

	column LIBVILLE
		dataType: string
		lineageTag: c460af7d-8c8a-46bb-8809-2528cf87d152
		summarizeBy: none
		sourceColumn: LIBVILLE

		annotation SummarizationSetBy = Automatic

	column DEP
		dataType: int64
		formatString: 0
		lineageTag: d9a2a35a-c498-4b6a-8d61-c196b994818e
		summarizeBy: sum
		sourceColumn: DEP

		annotation SummarizationSetBy = Automatic

	column ville_dep_pays
		dataType: string
		lineageTag: 0b0de3f3-441d-4921-936d-200ac16dbb90
		summarizeBy: none
		sourceColumn: ville_dep_pays

		annotation SummarizationSetBy = Automatic

	column SD
		dataType: double
		lineageTag: a635abbb-0483-4f40-82d8-3644404df039
		summarizeBy: sum
		sourceColumn: SD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SC
		dataType: double
		lineageTag: 1001198b-8bba-463d-969e-849c52be8da2
		summarizeBy: sum
		sourceColumn: SC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column solde
		dataType: double
		lineageTag: 4956e91e-c148-4891-871e-187c2c51dccd
		summarizeBy: sum
		sourceColumn: solde

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BASE_FILCAL_FNB
		dataType: double
		lineageTag: 5afc277c-27bf-4154-afd7-cfcb69bbf4ce
		summarizeBy: sum
		sourceColumn: BASE_FILCAL_FNB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BASE_FILCAL_FB
		dataType: double
		lineageTag: 04ba4328-af4f-4dac-9522-949f63d77c2a
		summarizeBy: sum
		sourceColumn: BASE_FILCAL_FB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TAUX_FILCAL_COM_FB
		dataType: int64
		formatString: 0
		lineageTag: e35444f9-1864-4f55-9fe9-5184bcaeb434
		summarizeBy: sum
		sourceColumn: TAUX_FILCAL_COM_FB

		annotation SummarizationSetBy = Automatic

	column TAUX_FILCAL_COM_FNB
		dataType: double
		lineageTag: 9bf42b82-6f04-40e6-940d-9dff88d8557d
		summarizeBy: sum
		sourceColumn: TAUX_FILCAL_COM_FNB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BASE_FILCAL
		dataType: double
		lineageTag: 43a37651-83e4-45ce-a918-51892301b3b6
		summarizeBy: sum
		sourceColumn: BASE_FILCAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REC_FILCAL_COM
		dataType: double
		lineageTag: 7ccd3708-c5df-4473-94de-71b1e239919d
		summarizeBy: sum
		sourceColumn: REC_FILCAL_COM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TAUX_FILCAL_MEL_FB
		dataType: int64
		formatString: 0
		lineageTag: 20351570-4072-4621-a1bd-d5c68ffadcf8
		summarizeBy: sum
		sourceColumn: TAUX_FILCAL_MEL_FB

		annotation SummarizationSetBy = Automatic

	column TAUX_FILCAL_MEL_FNB
		dataType: double
		lineageTag: b91051e8-b2a0-4a91-9b48-96749e67fa68
		summarizeBy: sum
		sourceColumn: TAUX_FILCAL_MEL_FNB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REC_FILCAL_MEL
		dataType: double
		lineageTag: 819d2dde-4ef2-45bc-973f-e9375ffc69ad
		summarizeBy: sum
		sourceColumn: REC_FILCAL_MEL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SIREPCI
		dataType: int64
		formatString: 0
		lineageTag: ab4572c6-e7f7-4b1e-be5d-0f0917b33aec
		summarizeBy: sum
		sourceColumn: SIREPCI

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Formation\crise_immo\finances_publiques_mel.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"LIB_COM_POSTAL", type text}, {"LIBCOM", type text}, {"LIBVILLE", type text}, {"DEP", Int64.Type}, {"ville_dep_pays", type text}, {"SD", type number}, {"SC", type number}, {"solde", type number}, {"BASE_FILCAL_FNB", type number}, {"BASE_FILCAL_FB", type number}, {"TAUX_FILCAL_COM_FB", Int64.Type}, {"TAUX_FILCAL_COM_FNB", type number}, {"BASE_FILCAL", type number}, {"REC_FILCAL_COM", type number}, {"TAUX_FILCAL_MEL_FB", Int64.Type}, {"TAUX_FILCAL_MEL_FNB", type number}, {"REC_FILCAL_MEL", type number}, {"SIREPCI", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

