table Constat_SDF_France
	lineageTag: 2b0dbafd-3076-4882-9252-23cb648d8f0c

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 80f91d72-1d50-4f88-b687-bcfa90835e48
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: int64
		formatString: 0
		lineageTag: 730ac090-d883-41fa-9eff-2b892070da4a
		summarizeBy: sum
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Constat_SDF_France = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\LeWagon\Projet_crise_logement\dataset_bi\Constat_SDF_France.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", Int64.Type}, {"Column2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

