table HomelessnessRate
	lineageTag: 346379d8-5e68-4381-a856-0496afa10bf5

	column Entity
		dataType: string
		lineageTag: e82faad5-f944-4c1a-aed6-8aea8142ecc9
		summarizeBy: none
		sourceColumn: Entity

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: 04f77ac1-3028-4053-9a7b-330d9f74a014
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 51896c69-287d-4ffd-be1b-2a8bd388ed95
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column streets
		dataType: double
		lineageTag: 15ddf0a4-aff2-4f7b-a006-66f80592f691
		summarizeBy: sum
		sourceColumn: streets

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shelters
		dataType: double
		lineageTag: e4d039ca-c409-4b7e-9c8f-62a32036651e
		summarizeBy: sum
		sourceColumn: shelters

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Either
		dataType: double
		lineageTag: db49ed20-dd78-4138-9478-fee785bfd6ba
		summarizeBy: sum
		sourceColumn: Either

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition HomelessnessRate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\LeWagon\Projet_crise_logement\dataset_bi\homelessness_rate.xlsx"), null, true),
				    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"streets", type number}, {"shelters", type number}, {"Either", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

